package io.liamju.tangshi.data.source.local;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import io.liamju.tangshi.data.Poetry;

import io.liamju.tangshi.data.source.local.PoetryDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig poetryDaoConfig;

    private final PoetryDao poetryDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        poetryDaoConfig = daoConfigMap.get(PoetryDao.class).clone();
        poetryDaoConfig.initIdentityScope(type);

        poetryDao = new PoetryDao(poetryDaoConfig, this);

        registerDao(Poetry.class, poetryDao);
    }
    
    public void clear() {
        poetryDaoConfig.clearIdentityScope();
    }

    public PoetryDao getPoetryDao() {
        return poetryDao;
    }

}
